url: https://streamweaver.github.io
baseurl: ""

# Site settings
title: Scott Turnbull
email: streamweaver@gmail.com
description: "Career information about Scott Turnbull"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0066cc
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Scott Turnbull
  pic: 4
  position: Founder
  social:
    - title: twitter
      url: https://twitter.com/Streamweaver
    - title: stack-overflow
      url: http://stackoverflow.com/users/542146/streamweaver
    - title: github
      url: https://github.com/Streamweaver
    - title: wordpress
      url: http://www.flagonwiththedragon.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Streamweaver
  - title: stack-overflow
    url: http://stackoverflow.com/users/542146/streamweaver
  - title: github
    url: https://github.com/Streamweaver
  - title: linkedin
    url: https://www.linkedin.com/pub/scott-turnbull/8/1b/b2b

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
